### ISSUE TITLE
NRD support in SL using Vulkan

### ISSUE THREAD

**Issue by BattleAxeVR** [nvpro-samples/vk_streamline#1]
Hi Neil, thanks for this sample, I had some problems with my path tracer and some extensions working in Vulkan, and getting DLSS-G working.

I was wondering, any chance you could add NRD to this? I know SL supports NRD "in theory" but the samples there are incomplete and simply do not work. I spent a couple days trying to debug it deep inside SL to no avail. The SL docs and howtos don't specify the SL inputs to NRD outputs mappings in terms of which enums get mapped to what, and I wasted more time trying to use SL for NRD than I did just updating my direct NRD integration (which Nvidia's own Path Tracking SDK doesn't even use SL for the NRD part, for some weird, inexplicable reason. I can only think because NRD simply doesn't work properly with both DX12 and Vulkan inside SL yet).

I know Ray Reconstruction is coming soon that makes NRD obsolete, at least on Nvidia GPUs, but for AMD I need a fallback denoiser and NRD isn't tied to DLSS / NV GPUs, so I need it to work. Any chance you could help? I just need a working VK + SL + NRD sample, or even just some basic documentation which is sorely lacking. I spent / wasted so much time over the past two years keeping NRD up to date in my engine and eventually gave up. The overhead on my company time to maintain that lib is too much. I need want to use SL for everything and end it.

**Comment by BattleAxeVR** [comment]
To wit, I opened this issue in the official SL repo on July 14th and nobody even responded yet.

I don't even know if I was wasting my own time trying to use SL + NRD + VK at the same time, or if it even works. It appears not to, there are comments in the actual source that suggest it doesn't work at all. I could really use a little help unblocking me, if you have a little time to spare. Thanks in advance.

https://github.com/NVIDIAGameWorks/Streamline_Sample/issues/4

**Comment by BattleAxeVR** [comment]
@NBickford-NV Hi Neil, you mentioned you guys would look at this, any news? I don't have NRD OR DLSS-RR working right now and it's holding up production on my game. If not, I'll have to reintegrate NRD the direct way which is a nightmare to maintain (inscrutable, hard to debug crashes).

**Comment by NBickford-NV** [comment]
Hi @BattleAxeVR ! Yep, still hoping to look into this, no news yet. Sorry, I've got a bit of a large backlog, but I will get to it (apologies for the wait)!

**Comment by BattleAxeVR** [comment]
No worries and happy new year, again.


*Battle Axe Games / VR. *

CEO: Bela Kampis ***@***.***>
VR Consultant
Montreal, Canada
Tel.: 514-264-8437
<https://battleaxevr.wordpress.com/>
<https://www.linkedin.com/in/brokenwings1977/>
<https://twitter.com/BattleAxeVR>   <https://www.facebook.com/battleaxevr/>

**Comment by BattleAxeVR** [comment]
@NBickford-NV Just in passing, you wouldn't happen to know whether SER actually works in Vulkan or not, would you? It's listed/ enumerated but apparently doesn't actually do anything, whereas on DX12 it nearly doubles the framerate. I'm really regretting using vulkan for my project, it's always getting features late or that half work or just don't work at all.

**Comment by NBickford-NV** [comment]
@BattleAxeVR It should have an effect -- maybe you could compare your code against the sample we have for it at https://github.com/nvpro-samples/vk_mini_samples/tree/main/samples/ser_pathtrace ?

**Comment by BattleAxeVR** [comment]
I tried ser_pathtrace and Path Tracing SDK, both don't have any effect enabling SER on Vulkan, only on DX12.

https://github.com/NVIDIAGameWorks/Path-Tracing-SDK/issues/2

I tried using latest game ready drivers and latest beta drivers and the feature simply has no effect on Vulkan, whatsoever. It must be broken in the driver or maybe there's some code broken somewhere else, that's what I'd like to know.

**Comment by NBickford-NV** [comment]
Ah! I see you've made an issue at https://github.com/nvpro-samples/vk_mini_samples/issues/8; let's move this part of the conversation over there.

**Comment by BattleAxeVR** [comment]
got it!

one last Q, how can I get DLSS DLLs for my title? It says I need to contact my Nvidia rep, but I don't have one.

**Comment by BattleAxeVR** [comment]
@NBickford-NV Just a quick Question Neil, if you don't mind: As far as you know does SL + NRD actually work in Vulkan? Or is it still WIP. I'm not talking about the vk_streamline sample here supporting NRD as the denoiser through SL (rather than direct integration), I'm talking about SL 2.2.1 plugin that actually works 100%, and tested. I can't really afford to spend more time on this, until I know something has changed in the SL plugin repo which is hasn't in the past five months.

I honestly regret picking Vulkan as my engine's language as the samples typically take 6-12 months to reach feature / performance parity with DX12 on PC. 

I really hope NRD via SL on VK can be fixed so I can use it as a fallback for GPUs that don't support DLSS-RR, or in case I need to modify it. But I can't go back to direct NRD integration, it's too frustrating to debug the issues I'm having and don't have time to do that anyway. Any help you could give me would be greatly appreciated.

**Comment by NBickford-NV** [comment]
Let me check with @nvmheyer . I think we realized we'd need to do some deeper modifications to this sample to show off SL + NRD + Vulkan; since the frames in this sample are rasterized, there's no noise.

**Comment by HerveRV** [comment]
> @NBickford-NV Just a quick Question Neil, if you don't mind: As far as you know does SL + NRD actually work in Vulkan? Or is it still WIP. I'm not talking about the vk_streamline sample here supporting NRD as the denoiser through SL (rather than direct integration), I'm talking about SL 2.2.1 plugin that actually works 100%, and tested. I can't really afford to spend more time on this, until I know something has changed in the SL plugin repo which is hasn't in the past five months.
> 
> I honestly regret picking Vulkan as my engine's language as the samples typically take 6-12 months to reach feature / performance parity with DX12 on PC.
> 
> I really hope NRD via SL on VK can be fixed so I can use it as a fallback for GPUs that don't support DLSS-RR, or in case I need to modify it. But I can't go back to direct NRD integration, it's too frustrating to debug the issues I'm having and don't have time to do that anyway. Any help you could give me would be greatly appreciated.

I so agree with you, i spend so much time, and it's hard to make things work. Whatever i try with NRD + SL crash in slEvaluateFeature.

![RV - 2024-03-12 18H11m08](https://github.com/nvpro-samples/vk_streamline/assets/2123442/b326f07f-8f20-4458-b146-746319a6a6f0)

**Comment by NBickford-NV** [comment]
Hi @BattleAxeVR,

Looks like a direct NRD integration is the way to go -- @nvmheyer is working on a sample to show NRD in Vulkan. I just got word from the Streamline team that the NRD plugin for Streamline is no longer being developed, but I'm probably going to keep on trying to see if I can add it to this sample.

Good news is that I fixed a bug with the motion vectors in this sample -- those changes should be pushed here soon.

Thanks,

--Neil

**Comment by BattleAxeVR** [comment]
Thanks for the news. Another big reason I needed Streamline in the first place was because DLSS FrameGeneration requires it, but I'll see if I can work around that as well. I'd rather not maintain a wrapper that serves no real purpose. IMO it should either be fully supported or abandoned completely. I don't understand why DLSS-FG ever required SL in the first place. All this stuff adds dev overhead and in practice, adding a wrapper around other libs just means that's one more thing you have to maintain (and worse---debug).
